### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by artur-varosyan**
Hi, everyone I propose these changes for the structure of the README. We can discuss and change the visual details and app photos.

You can find the new README [here](https://github.com/spe-uob/2021-ARReshare/tree/updateREADME).

Improvements:
* Added status badges showing the _status of CI, the license, number of contributors, issues and pull requests_.
* Added a table of contents for easier navigation
* Updated the description of the project
* Added references and links to the backend for the app

### CODE REVIEW

**Review by Lingtao-Cai — APPROVED** [review]
Really professional and interactive Readme file!!!!

**Review by arfi2212 — APPROVED** [review]
Very professional bud! Love the new look :)

**Review by HellinSun — APPROVED** [review]
That looks amazing! Thanks Artur

**Review by Manoutofpower — APPROVED** [review]

**Comment by artur-varosyan** [comment]
Perfect, thank you for your comments.

**Pull request merged**
